# Generated by Django 5.1.2 on 2024-11-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catogery',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='catogery',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=15),
        ),
        migrations.AddField(
            model_name='catogery',
            name='total_product',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
