# Generated by Django 5.1.2 on 2024-12-10 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_product_price_product_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('WEIGHT', 'Weight-Based'), ('VOLUME', 'Volume-Based')], max_length=10, null=True)),
                ('weight', models.CharField(blank=True, choices=[('0.5', '0.5 kg'), ('1', '1 kg'), ('1.5', '1.5 kg'), ('2', '2 kg')], max_length=10, null=True)),
                ('volume', models.CharField(blank=True, choices=[('0.5', '0.5 liter'), ('1', '1 liter')], max_length=10, null=True)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='admin_panel.product')),
            ],
            options={
                'db_table': 'product_variants',
                'unique_together': {('product', 'weight', 'volume')},
            },
        ),
    ]
