# Generated by Django 5.1.2 on 2024-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_coupontable_couponusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('offer_type', models.CharField(choices=[('PRODUCT', 'Product Offer'), ('CATEGORY', 'Category Offer')], default='CATEGORY', max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
