# Generated by Django 5.1.2 on 2024-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='catogery',
            name='offers',
            field=models.ManyToManyField(null=True, related_name='categories', to='admin_panel.offer'),
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(null=True, related_name='products', to='admin_panel.offer'),
        ),
    ]
