# Generated by Django 5.1.2 on 2024-12-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_catogery_offers_product_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogery',
            name='offers',
            field=models.ManyToManyField(related_name='categories', to='admin_panel.offer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(related_name='products', to='admin_panel.offer'),
        ),
    ]
