# Generated by Django 5.1.2 on 2024-12-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_catogery_offers_alter_product_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catogery',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offers',
        ),
    ]
