# Generated by Django 5.1.2 on 2024-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_cart_unique_together_cart_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
