# Generated by Django 5.1.2 on 2024-12-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Poor Quality'), ('NOT_NEEDED', 'No Longer Needed')], max_length=20, null=True)),
                ('return_explanation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_proof', models.ImageField(blank=True, null=True, upload_to='return_proofs/')),
                ('order_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='user.orderitem')),
            ],
            options={
                'db_table': 'order_returns',
                'ordering': ['-created_at'],
            },
        ),
    ]
