# Generated by Django 5.1.2 on 2024-12-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_wallet_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('ORIGINAL_PAYMENT', 'Original Payment Method'), ('STORE_CREDIT', 'Store Credit'), ('WALLET', 'Wallet Balance')], max_length=20, null=True)),
                ('refund_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('refund_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, null=True)),
                ('order_return', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='user.orderreturn')),
            ],
        ),
    ]
