# Generated by Django 5.1.2 on 2024-12-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='user.orderreturn'),
        ),
    ]
