# Generated by Django 5.1.2 on 2024-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_refund_order_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('BANK_TRANSFER', 'Bank Transfer'), ('INTERNAL', 'Internal Transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
