# Generated by Django 5.1.2 on 2024-12-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_orderitem_payment_retry_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_retry_window',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_retry_window',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
